config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :destroy]
  resources :products do
    member do
      patch :restore
      post :add_to_cart
      post :buy_now
    end
    collection do
      delete :delete_selected
    end
  end
  resources :orders, only: [:create, :show] do
    member do
      patch :cancel
      patch :update_status
    end
  end
  resource :cart, only: [:show] do
    patch 'update_item/:id', to: 'carts#update_item', as: 'update_item'
    delete 'destroy_item/:id', to: 'carts#destroy_item', as: 'destroy_item'
  end

  resources :seller_dashboard, only: [:index]
  resources :buyer_dashboard, only: [:index]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
  delete 'deactivate_account/:id', to: 'users#destroy', as: 'deactivate_account'
  get 'reactivate/:id', to: 'reactivations#edit', as: 'reactivate_user'
  patch 'reactivate/:id', to: 'reactivations#update'

  post 'create_order_from_cart', to: 'orders#create', as: 'create_order_from_cart'

  root 'products#index'
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid

  has_secure_password
  has_one :buyer, dependent: :destroy
  has_one :seller, dependent: :destroy
  has_many :orders, through: :buyer

  validates :email, presence: true, uniqueness: true

  after_create :create_buyer_account

  def seller?
    !!seller
  end

  private

  def create_buyer_account
    Buyer.create(user: self)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      Seller.create(user: @user) if params[:user][:seller] == '1'
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Your account has been deactivated.'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h3 class="text-center">Sign Up</h3>
        </div>
        <div class="card-body">
          <%= form_with(model: @user, url: register_path, local: true) do |form| %>
            <div class="form-group">
              <%= form.label :email %>
              <%= form.email_field :email, class: 'form-control' %>
            </div>
            <div class="form-group mt-3">
              <%= form.label :password %>
              <%= form.password_field :password, class: 'form-control' %>
            </div>
            <div class="form-group mt-3">
              <%= form.label :password_confirmation %>
              <%= form.password_field :password_confirmation, class: 'form-control' %>
            </div>
            <div class="form-check mt-3">
              <%= form.check_box :seller %>
              <%= form.label :seller, "Sign up as a seller" %>
            </div>
            <div class="form-group mt-3">
              <%= form.submit "Sign Up", class: 'btn btn-primary w-100' %>
            </div>
          <% end %>
        </div>
        <div class="card-footer text-center">
          <%= link_to "Login", login_path %> if you already have an account.
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>