config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :destroy]
  resources :products do
    member do
      patch :restore
      post :add_to_cart
      post :buy_now
    end
    collection do
      delete :delete_selected
    end
  end
  resources :orders, only: [:create, :show] do
    member do
      patch :cancel
      patch :update_status
    end
  end
  resource :cart, only: [:show] do
    patch 'update_item/:id', to: 'carts#update_item', as: 'update_item'
    delete 'destroy_item/:id', to: 'carts#destroy_item', as: 'destroy_item'
  end

  resources :seller_dashboard, only: [:index]
  resources :buyer_dashboard, only: [:index]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
  delete 'deactivate_account/:id', to: 'users#destroy', as: 'deactivate_account'
  get 'reactivate/:id', to: 'reactivations#edit', as: 'reactivate_user'
  patch 'reactivate/:id', to: 'reactivations#update'

  post 'create_order_from_cart', to: 'orders#create', as: 'create_order_from_cart'

  root 'products#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :buyer

  STATUSES = %w[pending confirmed shipped delivered cancelled].freeze

  validates :status, inclusion: { in: STATUSES }

  before_create :set_order_number
  after_create :reduce_product_stock

  def pending?
    status == 'pending'
  end

  def confirmed?
    status == 'confirmed'
  end

  def shipped?
    status == 'shipped'
  end

  def delivered?
    status == 'delivered'
  end

  def cancelled?
    status == 'cancelled'
  end

  private

  def set_order_number
    self.order_number = SecureRandom.hex(10)
  end

  def reduce_product_stock
    product.reduce_stock(quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create, :cancel, :update_status]

  def show
    @order = current_user.buyer.orders.find(params[:id])
  end

  def create
    @cart = current_user.buyer.cart
    @cart.cart_items.each do |cart_item|
      order = current_user.buyer.orders.new(product: cart_item.product, quantity: cart_item.quantity, total_price: cart_item.quantity * cart_item.product.price, status: 'pending')
      order.save
      cart_item.product.reduce_stock(cart_item.quantity)
    end
    @cart.cart_items.destroy_all
    redirect_to buyer_dashboard_index_path, notice: 'Order was successfully placed.'
  end

  def cancel
    @order = current_user.buyer.orders.find(params[:id])
    if @order.pending?
      @order.update(status: 'cancelled')
      @order.product.increase_stock(@order.quantity)
      redirect_to buyer_dashboard_index_path, notice: 'Order was successfully cancelled.'
    else
      redirect_to buyer_dashboard_index_path, alert: 'Order cannot be cancelled.'
    end
  end

  def update_status
    @order = Order.find(params[:id])
    if @order.update(status: params[:status])
      redirect_to seller_dashboard_index_path, notice: 'Order status was successfully updated.'
    else
      redirect_to seller_dashboard_index_path, alert: 'There was an issue updating the order status.'
    end
  end

  private

  def authenticate_user!
    redirect_to login_path, alert: 'You need to sign in or sign up before continuing.' unless current_user
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :buyer_id, style: "display: block" %>
    <%= form.text_field :buyer_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :total_price, style: "display: block" %>
    <%= form.text_field :total_price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Product:</strong>
    <%= order.product_id %>
  </p>

  <p>
    <strong>Buyer:</strong>
    <%= order.buyer_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= order.quantity %>
  </p>

  <p>
    <strong>Total price:</strong>
    <%= order.total_price %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<h1>Order Details</h1>

<p>
  <strong>Order Number:</strong>
  <%= @order.order_number %>
</p>

<p>
  <strong>Ordered At:</strong>
  <%= @order.created_at.strftime("%B %d, %Y") %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status.capitalize %>
</p>

<p>
  <strong>Product:</strong>
  <%= link_to @order.product.name, product_path(@order.product) %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Total Price:</strong>
  $<%= @order.total_price %>
</p>

<% if @order.status != 'cancelled' %>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#cancelOrderModal">
    Cancel Order
  </button>
<% end %>

<!-- Modal -->
<div class="modal fade" id="cancelOrderModal" tabindex="-1" aria-labelledby="cancelOrderModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cancelOrderModalLabel">Cancel Order</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to cancel this order?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= link_to 'Yes, Cancel Order', cancel_order_path(@order), method: :patch, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Back to Orders', buyer_dashboard_index_path, class: 'btn btn-secondary' %>