config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :destroy]
  resources :products do
    member do
      patch :restore
      post :add_to_cart
      post :buy_now
    end
    collection do
      delete :delete_selected
    end
  end
  resources :orders, only: [:create, :show] do
    member do
      patch :cancel
      patch :update_status
    end
  end
  resource :cart, only: [:show] do
    patch 'update_item/:id', to: 'carts#update_item', as: 'update_item'
    delete 'destroy_item/:id', to: 'carts#destroy_item', as: 'destroy_item'
  end

  resources :seller_dashboard, only: [:index]
  resources :buyer_dashboard, only: [:index]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
  delete 'deactivate_account/:id', to: 'users#destroy', as: 'deactivate_account'
  get 'reactivate/:id', to: 'reactivations#edit', as: 'reactivate_user'
  patch 'reactivate/:id', to: 'reactivations#update'

  post 'create_order_from_cart', to: 'orders#create', as: 'create_order_from_cart'

  root 'products#index'
end

app/controllers/buyer_dashboard_controller.rb
class BuyerDashboardController < ApplicationController
  before_action :authenticate_buyer!

  def index
    @orders = current_user.buyer.orders.includes(:product)
    @cart = current_user.buyer.cart || current_user.buyer.create_cart
  end

  private

  def authenticate_buyer!
    unless current_user&.buyer
      redirect_to root_path, alert: 'You are not authorized to access this page.'
    end
  end
end

app/helpers/buyer_dashboard_helper.rb
module BuyerDashboardHelper
end

app/views/buyer_dashboard/index.html.erb
<h1>Mon espace achat</h1>

<h2>Mes commandes passées</h2>
<table class="table">
  <thead>
  <tr>
    <th>Order Number</th>
    <th>Ordered At</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.order_number %></td>
      <td><%= order.created_at.strftime("%B %d, %Y") %></td>
      <td><%= order.status.capitalize %></td>
      <td>
        <%= link_to 'View', order_path(order), class: 'btn btn-sm btn-outline-secondary' %>
        <% if order.pending? %>
          <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#cancelOrderModal<%= order.id %>">
            Cancel
          </button>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<h2>Mon panier actuel</h2>
<% if @cart && @cart.cart_items.any? %>
  <table class="table">
    <thead>
    <tr>
      <th>Product Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @cart.cart_items.each do |cart_item| %>
      <tr>
        <td><%= link_to cart_item.product.name, product_path(cart_item.product) %></td>
        <td>
          <%= form_with url: update_item_cart_path(cart_item), method: :patch, local: true do |f| %>
            <%= f.number_field :quantity, value: cart_item.quantity, min: 1, max: cart_item.product.stock, class: 'form-control d-inline-block w-25 me-2' %>
            <%= f.submit 'Update', class: 'btn btn-primary btn-sm' %>
          <% end %>
        </td>
        <td>$<%= cart_item.product.price %></td>
        <td>$<%= cart_item.quantity * cart_item.product.price %></td>
        <td>
          <%= link_to 'Remove', destroy_item_cart_path(cart_item), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <p><strong>Total:</strong> $<%= @cart.cart_items.sum { |item| item.quantity * item.product.price } %></p>
  <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#checkoutModal">
    Proceed to Checkout
  </button>
<% else %>
  <p>Votre panier est vide.</p>
<% end %>

<%= link_to 'Continue Shopping', products_path, class: 'btn btn-primary' %>

<!-- Cancel Order Modal -->
<% @orders.each do |order| %>
  <div class="modal fade" id="cancelOrderModal<%= order.id %>" tabindex="-1" aria-labelledby="cancelOrderModalLabel<%= order.id %>" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="cancelOrderModalLabel<%= order.id %>">Cancel Order</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to cancel this order?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= link_to 'Cancel Order', cancel_order_path(order), method: :patch, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<!-- Checkout Modal -->
<div class="modal fade" id="checkoutModal" tabindex="-1" aria-labelledby="checkoutModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="checkoutModalLabel">Confirm Checkout</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to proceed to checkout?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= link_to 'Checkout', create_order_from_cart_path, method: :post, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>