config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :destroy]
  resources :products do
    member do
      patch :restore
      post :add_to_cart
      post :buy_now
    end
    collection do
      delete :delete_selected
    end
  end
  resources :orders, only: [:create, :show] do
    member do
      patch :cancel
      patch :update_status
    end
  end
  resource :cart, only: [:show] do
    patch 'update_item/:id', to: 'carts#update_item', as: 'update_item'
    delete 'destroy_item/:id', to: 'carts#destroy_item', as: 'destroy_item'
  end

  resources :seller_dashboard, only: [:index]
  resources :buyer_dashboard, only: [:index]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'
  delete 'deactivate_account/:id', to: 'users#destroy', as: 'deactivate_account'
  get 'reactivate/:id', to: 'reactivations#edit', as: 'reactivate_user'
  patch 'reactivate/:id', to: 'reactivations#update'

  post 'create_order_from_cart', to: 'orders#create', as: 'create_order_from_cart'

  root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid

  belongs_to :seller
  has_many :cart_items
  has_many :orders

  def reduce_stock(amount)
    update(stock: stock - amount)
  end

  def increase_stock(amount)
    update(stock: stock + amount)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :restore, :add_to_cart, :buy_now]
  before_action :authorize_seller!, only: [:edit, :update, :destroy, :restore]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.seller = current_user.seller
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully deleted.'
  end

  def restore
    @product.restore
    redirect_to seller_dashboard_index_path, notice: 'Product was successfully restored.'
  end

  def add_to_cart
    cart = current_user.buyer.cart || current_user.buyer.create_cart
    cart_item = cart.cart_items.find_or_initialize_by(product: @product)
    cart_item.quantity = (cart_item.quantity || 0) + params[:quantity].to_i
    if cart_item.save
      redirect_to cart_path, notice: 'Product was successfully added to your cart.'
    else
      redirect_to @product, alert: 'There was an issue adding the product to your cart.'
    end
  end

  def buy_now
    quantity = params[:quantity].to_i
    order = current_user.buyer.orders.new(product: @product, quantity: quantity, total_price: @product.price * quantity, status: 'pending')
    if order.save
      redirect_to order_path(order), notice: 'Product was successfully purchased.'
    else
      redirect_to @product, alert: 'There was an issue with your purchase.'
    end
  end

  private

  def set_product
    @product = Product.with_deleted.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock)
  end

  def authorize_seller!
    unless current_user&.seller? && @product.seller == current_user.seller
      redirect_to products_path, alert: 'You are not authorized to perform this action.'
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.label :seller_id, style: "display: block" %>
    <%= form.text_field :seller_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= product.stock %>
  </p>

  <p>
    <strong>Seller:</strong>
    <%= product.seller_id %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= form_with(model: @product, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :stock %>
    <%= form.number_field :stock, class: 'form-control' %>
  </div>
  <div class="form-group mt-3">
    <%= form.submit "Update Product", class: 'btn btn-primary' %>
    <%= link_to 'Back', products_path, class: 'btn btn-secondary ms-2' %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1 class="my-4">Products</h1>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <h5 class="card-title"><%= link_to product.name, product %></h5>
          <p class="card-text"><strong>Description:</strong> <%= product.description.truncate(100) %></p>
          <p class="card-text"><strong>Price:</strong> $<%= product.price %></p>
          <p class="card-text"><strong>Stock:</strong> <%= product.stock %></p>

          <% if current_user && current_user.buyer %>
            <div class="d-flex flex-column">
              <%= form_with url: add_to_cart_product_path(product), method: :post, local: true, class: 'd-flex align-items-center mb-2' do |f| %>
                <%= f.number_field :quantity, value: 1, min: 1, max: product.stock, class: 'form-control me-2', style: 'width: 60px;', disabled: product.stock <= 0 %>
                <%= f.submit 'Add to Cart', class: 'btn btn-primary btn-sm flex-grow-1', disabled: product.stock <= 0 %>
              <% end %>
              <%= form_with url: buy_now_product_path(product), method: :post, local: true, class: 'd-flex align-items-center' do |f| %>
                <%= f.number_field :quantity, value: 1, min: 1, max: product.stock, class: 'form-control me-2', style: 'width: 60px;', disabled: product.stock <= 0 %>
                <%= f.submit 'Buy Now', class: 'btn btn-success btn-sm flex-grow-1', disabled: product.stock <= 0 %>
              <% end %>
            </div>
          <% end %>

          <% if current_user&.seller? && product.seller == current_user.seller %>
            <div class="d-flex justify-content-between mt-2">
              <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-warning btn-sm flex-grow-1 me-2' %>
              <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm flex-grow-1' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Product', new_product_path, class: 'btn btn-primary my-4' if current_user&.seller? %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_with(model: @product, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :stock %>
    <%= form.number_field :stock, class: 'form-control' %>
  </div>
  <div class="form-group mt-3">
    <%= form.submit "Create Product", class: 'btn btn-primary' %>
    <%= link_to 'Back', products_path, class: 'btn btn-secondary ms-2' %>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body text-center">
          <h1 class="card-title"><%= @product.name %></h1>

          <p class="card-text"><strong>Description:</strong></p>
          <p class="card-text"><%= @product.description %></p>

          <p class="card-text"><strong>Price:</strong> $<%= @product.price %></p>
          <p class="card-text"><strong>Stock:</strong> <%= @product.stock %></p>

          <div class="my-4">
            <%= link_to 'Back', products_path, class: 'btn btn-secondary me-2' %>

            <% if current_user && current_user.buyer %>
              <%= form_with url: add_to_cart_product_path(@product), method: :post, local: true, class: 'd-inline' do |f| %>
                <%= f.number_field :quantity, value: 1, min: 1, max: @product.stock, class: 'form-control d-inline-block w-auto me-2', style: 'width: 100px;', disabled: @product.stock <= 0 %>
                <%= f.submit 'Add to Cart', class: 'btn btn-primary', disabled: @product.stock <= 0 %>
              <% end %>
              <%= form_with url: buy_now_product_path(@product), method: :post, local: true, class: 'd-inline' do |f| %>
                <%= f.number_field :quantity, value: 1, min: 1, max: @product.stock, class: 'form-control d-inline-block w-auto me-2', style: 'width: 100px;', disabled: @product.stock <= 0 %>
                <%= f.submit 'Buy Now', class: 'btn btn-success', disabled: @product.stock <= 0 %>
              <% end %>
            <% end %>

            <% if current_user&.seller? && @product.seller == current_user.seller %>
              <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-warning me-2' %>
              <%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>